#!/bin/bash

if [ "$#" -ne 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

path=$1
destip=$2
user=$3
file_to_transfer=$4

scp -i "$path" "$file_to_transfer" "${user}@${destip}:"
