#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, (username)(user id) (Home directory path for the user)

$file="/etc/passwd"
while [ -e $file ];
do
	cut -d: -f1,3,6 /etc/passwd
done
