#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, (username)(user id) (Home directory path for the user
cut -d: -f1,3,6 /etc/passwd | while read -r line;
do
	echo "$line"
done
