#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but for the 9th iteration, displays Best School and then Hi on a new line.

count=1
while [ $count -le 11 ];
do
	if [ $count -eq 10 ];then
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done
